<form method="post" action="<?=App::config('url')?>korisnik/novi">
    <h4 class="text-center" style="margin-top: 10px;">Dodavanje novog korisnika</h4>
    <label>Ime
        <input type="text" name="ime" value="<?=$korisnik->ime?>" placeholder="Ime">
    </label>
    <label>Prezime
        <input type="text" name="prezime" value="<?=$korisnik->prezime?>" placeholder="Prezime">
    </label>
    <label>OIB
        <input type="number" name="oib" value="<?=$korisnik->oib?>" placeholder="OIB">
    </label>
    <label class="drzava">Država
        <?php include_once 'drzaveDropdown.phtml'; ?>
    </label>
    <label>Grad
        <input type="text" name="grad" value="<?=$korisnik->grad?>" placeholder="Grad">
    </label>
    <label>Poštanski broj
        <input type="number" name="postanski_broj" value="<?=$korisnik->postanski_broj?>" placeholder="Poštanski broj">
    </label>
    <label>Ulica
        <input type="text" name="ulica" value="<?=$korisnik->ulica?>" placeholder="Ulica">
    </label>
    <label>Kućni broj
        <input type="text" name="kucni_broj" value="<?=$korisnik->kucni_broj?>" placeholder="Kućni broj">
    </label>
    <label>Email
        <input type="email" name="email" value="<?=$korisnik->email?>" placeholder="Email">
    </label>
    <label>Datum rođenja
        <input type="date" name="datum_rodenja" value="<?=$korisnik->datum_rodenja?>" placeholder="Datum rođenja">
    </label>
    <label>Broj telefona
        <input type="text" name="broj_telefona" value="<?=$korisnik->broj_telefona?>" placeholder="Broj telefona">
    </label>
    <label>Spol
        <input type="text" name="spol" value="<?=$korisnik->spol?>" placeholder="Spol">
    </label>

    <?=$poruka?>

    <div class="grid-x grid-padding-x">
        <div class="cell large-6">
            <a class="alert button expanded" href="<?=App::config('url')?>korisnik">Odustani</a>
        </div>
        <div class="cell large-6">
            <input type="submit" class="success button expanded" value="Dodaj"></input>  
        </div>
    </div>
</form>