<form method="post" action="<?=App::config('url')?>narudzba/promjena/<?=$e->sifra?>">

    <div class="grid-x grid-padding-x">
        <div class="large-4 cell">
            <?php include_once 'opciPodaci.phtml'; ?>
        </div>
        <div class="large-8 cell">
            <?php include_once 'proizvodi.phtml'; ?>
        </div>
    </div>
            
    <?=$poruka?>

    <div class="grid-x grid-padding-x">
        <div class="large-6 cell">
            <a class="alert button expanded" 
                href="<?=App::config('url')?>narudzba">Odustani</a>
        </div>
        <div class="large-6 cell">
            <input type="submit" class="button expanded" value="Spremi"></input>
        </div>
    </div>

</form>