<a href="<?=App::config('url')?>narudzba/nova" class="success button expanded">Dodaj novu narudžbu</a>
<table class="tablica">
    <thead>
        <tr>
            <th>Broj praćenja</th>
            <th>Datum narudžbe</th>
            <th>Datum isporuke</th>
            <th>Korisnik</th>
            <th>Akcija</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($entiteti as $e): ?>
            <tr>
                <td><?=$e->broj_pracenja?></td>
                <td><?=$e->datum_narudzbe?></td>
                <td><?=$e->datum_isporuke?></td>
                <td><?=$e->korisnik?></td>
                <td>
                        <a href="<?=App::config('url')?>narudzba/promjena/<?=$e->sifra?>">
                            <i style="color: blue; font-size: 20px;" class="fi-pencil"></i>
                        </a>
                        &nbsp;&nbsp;
                        <?php if($e->stavke==0): ?>
                            <a onclick="return confirm('Sigurno želite obrisati narudžbu <?=$e->broj_pracenja?>?');"
                            href="<?=App::config('url')?>narudzba/brisanje/<?=$e->sifra?>">
                                <i style="color: red; cursor: pointer; font-size: 20px;" class="fi-trash"></i>
                            </a>
                            <?php else: ?>
                                <a href="<?=App::config('url')?>narudzba/brisanje/<?=$e->sifra?>">
                                <i style="color: gray; font-size: 20px;" 
                                title="Narudžba se ne može obrisati jer se nalazi na jednoj ili više stavki."
                                class="fi-trash"></i>
                            </a>
                       <?php endif; ?>
                </td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>