<form method="post" action="<?=App::config('url')?>kategorija/promjena/<?=$e->sifra?>">
    <h4 class="text-center">Detalji kategorije</h4>

    <label>Naziv
        <input type="text" name="naziv" value="<?=$e->naziv?>"/>
    </label>

    <label>Opis
        <input type="text" name="opis" value="<?=$e->opis?>"/>
    </label>

    <?=$poruka?>

    <div class="grid-x grid-padding-x">
        <div class="large-6 cell">
            <a class="alert button expanded" href="<?=App::config('url')?>kategorija">Odustani</a>
        </div>
        <div class="large-6 cell">
            <input type="submit" class="button expanded" value="Spremi"></input>
        </div>
    </div>
</form>