<form method="post" enctype="multipart/form-data" 
    action="<?=App::config('url')?>proizvod/promjena/<?=$e->sifra?>">
<h4 class="text-center">Detalji proizvoda</h4>

<label>Naziv
        <input type="text" name="naziv" id="naziv" value="<?=$e->naziv?>"/>
</label>
<label>Vrsta
    <input type="text" name="vrsta" value="<?=$e->vrsta?>"/>
</label>
<label>Cijena
    <input type="text" name="cijena" value="<?=$e->cijena?>"/>
</label>
<label>Boja
    <input type="text" name="boja" value="<?=$e->boja?>"/>
</label>
<label>Tezina
    <input type="text" name="tezina" value="<?=$e->tezina?>"/>
</label>

<label>Kategorija</label>
    <select name="kategorija" id="kategorija">
        <?php foreach($kategorije as $k): ?>
            <option
            <?php if($e->kategorija == $k->sifra){
                echo ' selected=="selected"';
            }
            ?> 
            value="<?=$k->sifra?>"><?=$k->naziv?></option>
        <?php endforeach; ?>
    </select>

<label>Slika (.jpg)
    <input type="file" name="slika">
</label>
<img src="<?=$e->slika?>" alt="">

<?=$poruka?>

  <div class="grid-x grid-padding-x">
    <div class="large-6 cell">
        <a class="alert button expanded" 
            href="<?=App::config('url')?>proizvod">Odustani</a>
    </div>
    <div class="large-6 cell">
        <input type="submit" class="button expanded" value="Spremi"></input>
    </div>
  </div>

</form>